- src/app/chat/individual/[channelRoomId]/page.tsx
- src/app/chat/individual/page.tsx
- src/app/onboarding/interests/page.tsx
- src/components/onboarding/interests/UserPreferenceForm.tsx
- src/utils/format.ts
- #16
---
**온보딩 취향 선택**
*  step 변경 시 화면이 리렌더링 되지 않는 문제 수정
* 첫번째 페이지 헤더 뒤로가기 버튼 비활성화 (개인정보 api 두 번 호출되는 문제 방지)
**채팅방 상세페이지**
* 채팅방 내부 날짜 컴포넌트 실시간 데이터 반영
---
| 기능 유형     | 기능 개선 / 버그 수정   |
> v1 릴리즈 전 자잘한 수정 사항 반영

- .github/workflows/cicd-frontend.yml
- Actions 자동화 CICD 스크립트 추가. 현재 CD 및 Rollback까지 구현
---
> Actions CI/CD 스크립트 추가

- .github/workflows/cicd-frontend.yml
- src/app/globals.css
- src/components/matching/MatchingSignalInputBox.tsx
- src/components/onboarding/interests/UserPreferenceForm.tsx
- #30 
---
---
| 기능 유형     | 기능 개선 / 버그 수정         |
> iOS 환경 대응 및 온보딩 / 채팅 중복 처리 예외 로직 개선

- .github/workflows/cicd-frontend.yml
- Actions CICD 스크립트 중 배포환경(PROD, DEV) 구분이 안되는 오류 해결
---
> CICD 스크립트 중 배포환경(PROD, DEV) 구분 오류 해결

- .github/workflows/cicd-frontend.yml
- src/app/globals.css
- src/components/matching/MatchingSignalInputBox.tsx
- src/components/onboarding/interests/UserPreferenceForm.tsx
- src/lib/axios.ts
- #30
---
- 튜닝 페이지에서 채팅이 두 번 보내지는 문제 예외 처리
- iOS 가상키보드 화면 확대 방지
- 취향 등록 시 중복 호출 제한
- Refresh Token 만료 시 /login 페이지로 리다이렉트
---
| 기능 유형     | 버그 수정  |
> 온보딩 및 채팅 UX 안정화 및 예외 처리 개선

- next.config.ts
- package.json
- pnpm-lock.yaml
- src/app/login/page.tsx
- #59 
---
- `WebP`/`AVIF` 이미지 포맷 설정 및 `@next/bundle-analyzer` 적용
- 로그인 페이지 이미지에 priority 적용
---
| 기능 유형     | 신규 기능 / 기능 개선    |
> Next.js 이미지 포맷 최적화 및 번들 분석 도구 적용

- .github/workflows/docker-cicd-frontend.yml
- Dockerfile
[Sprint #6 - CL] - 프론트엔드 CI/CD 적용 [#321](https://github.com/100-hours-a-week/2-hertz-wiki/issues/321)
---
- 도커 파일 추가
- .dockerignore 추가
- docker-cicd-frontend.yml 추가
---
| 기능 유형     | 신규 기능        |
| 영향 범위     | 배포                              |
| 관련 파일     | workflows/*                      |
| 추가 리팩토링 | 없음  |
---
<!-- 추가로 공유하고 싶은 내용이 있다면 자유롭게 작성해주세요
- 완전한 전환 전이기 때문에 기존 cicd도 유지 하겠습니다.
> feat: 도커 CI/CD 적용

- .github/workflows/cicd-frontend.yml
- .github/workflows/docker-cicd-frontend.yml
[Sprint #6 - CL] - 프론트엔드 CI/CD 적용 [#321](https://github.com/100-hours-a-week/2-hertz-wiki/issues/321)
---
- 도커 파일 추가
- .dockerignore 추가
- docker-cicd-frontend.yml 추가
- pathignore 추가
---
| 기능 유형     | 신규 기능        |
| 영향 범위     | 배포                              |
| 관련 파일     | workflows/*                      |
| 추가 리팩토링 | 없음  |
---
<!-- 추가로 공유하고 싶은 내용이 있다면 자유롭게 작성해주세요
- 완전한 전환 전이기 때문에 기존 cicd도 유지 하겠습니다.
> fix: 백틱 제거, workflow ignore 추가

- .github/workflows/docker-cicd-frontend.yml
프론트엔드 CI/CD 적용 https://github.com/100-hours-a-week/2-hertz-wiki/issues/321
---
- 이미지 주입 안되는 문제 해결
- 특정 리소스만 변경 되도록 수정
> feat: dev 환경 CI/CD 완성

- src/app/chat/individual/page.tsx
- src/components/layout/ClientLayoutContent.tsx
- src/lib/queryClient.ts
- #100
---
- 새 메시지 SSE 수신 시 채팅 목록 갱신을 위한 API 호출 로직 구현
- SSE 도입에 따른 채팅 목록 폴링 로직 제거
---
**SSE로 채팅 목록 실시간 갱신 구현한 영상**
https://github.com/user-attachments/assets/ecc69e44-de70-4d31-b407-6db3463df40d
---
| 기능 유형     | 신규 기능  |
> SSE 기반 채팅 목록 실시간 갱신 기능 추가 및 폴링 방식 제거

- .github/workflows/docker-cicd-frontend.yml
> refactor: 도커 CI/CD 최종 완성

- src/app/chat/individual/[channelRoomId]/page.tsx
- src/hooks/useSocketIO.ts
- #124 
- #125
---
- 메모리 누수 방지를 위한 명확한 리스너 제거 로직 추가
- 채팅 메시지가 두 번 렌더링되는 이슈 해결
---
| 기능 유형     | 기능 개선 / 버그 수정   |
> 채팅 메시지 중복 렌더링 및 socket 메모리 누수 이슈 해결

- package.json
- pnpm-lock.yaml
- src/app/chat/individual/[channelRoomId]/page.tsx
- src/app/mypage/page.tsx
- src/components/mypage/UserProfileCard.tsx
- src/lib/api/user.ts
- src/lib/schema/mypageValidation.ts
- #125
- #127
---
- `WebSocket` 리스너 누적에 따른 메모리 누수 문제 해결
- 마이페이지 한 줄 소개 수정 api 연결 로직 구현
- 한 줄 소개 입력값에 대한 zod 유효성 검사 정의
- 한 줄 소개 수정 기능 퍼블리싱 및 로직 구현
- `react-textarea-autosize` 라이브러리 설치
https://github.com/user-attachments/assets/aca7e031-3da3-472a-a0d5-031891eda93b
---
| 기능 유형     | 신규 기능 / UI 변경         |
> 마이페이지 한 줄 소개 수정 기능 구현 및 WebSocket 메모리 누수 해결

- src/app/chat/individual/[channelRoomId]/page.tsx
- src/app/layout.tsx
- src/app/matching/individual/page.tsx
- src/app/mypage/page.tsx
- src/components/home/BannerSection.tsx
- src/components/home/MatchTypeSelector.tsx
- src/components/onboarding/information/OnboardingInformationWrapper.tsx
- src/components/onboarding/information/UserInformationForm.tsx
- src/lib/api/matching.ts
- src/lib/api/onboarding.ts
- #134
---
- 카테고리 기반 매칭 api 연결 로직 구현
- 마이페이지 및 홈페이지 불필요한 스크롤 제거
- 메세지 중복 렌더링 방지를 위한 optimistic UI 제거
- 초대코드 예외처리 로직 수정
- Number 대소문자 lint 에러 해결
---
| 기능 유형     | 신규 기능 / 기능 개선 / 버그 수정 / UI 변경  |
> 카테고리 기반 매칭 API 연동 및 메시지 중복 렌더링 이슈 해결

- src/app/chat/individual/[channelRoomId]/page.tsx
- src/components/chat/common/ReceiverMessage.tsx
- src/lib/api/chat.ts
- #136
---
- 신고 api 연결 로직 구현
- 채팅 메세지 우클릭 시 신고 모달 호출 로직 구현
https://github.com/user-attachments/assets/b43bc072-480b-4d40-b794-b51d32b0d7f8
---
| 기능 유형     | 신규 기능  |
> 채팅 메세지 우클릭 시 신고 모달 및 API 연결 로직 구현

- src/app/alarm/page.tsx
- src/app/chat/individual/page.tsx
- src/app/mypage/page.tsx
- src/components/matching/MatchingSignalInputBox.tsx
- src/components/onboarding/information/MatchingAgreementToggleGroup.tsx
- src/lib/api/alarm.ts
- src/lib/api/chat.ts
- src/lib/api/matching.ts
- src/lib/api/user.ts
- #138
---
- 마이페이지 매칭 수정 api 연결
- 시그널 전송 시 카테고리 포함하도록 v3 API 연동
- 채팅방 목록에 카테고리 표시 추가
- 알람 페이지 ALERT 필드 추가
- 마이페이지 토글 버튼 이모지 제거
https://github.com/user-attachments/assets/8f559910-4110-42ac-8796-98f5104762bc
---
| 기능 유형     | 신규 기능 / 기능 개선 / UI 변경   |
>  마이페이지 매칭 수정 및 시그널 · 채팅 · 알람 기능 개선

- src/app/chat/individual/[channelRoomId]/page.tsx
- src/components/layout/ClientLayoutContent.tsx
- src/constants/sseHandlers.tsx
- src/contexts/SSEContext.tsx
- src/hooks/useSSE.ts
- src/hooks/useSSEReconnector.ts
- src/stores/useSSEStore.ts
- src/types/chat.ts
- #140
---
SSE 핸들러 분리 및 SSE 이벤트 미감지 이슈 해결
- getSSEHandlers 내 window.location.pathname 사용으로 실시간 채팅방 감지
- 최초 채팅방 ID 고정되는 문제 해결
- SSE 핸들러 생성 시 pathname 클로저 참조 제거
- 관련 로직 리팩토링 및 안정성 향상
NewMessageType 타입 분리
---
| 기능 유형     | 기능 개선 / 버그 수정  |
> SSE 이벤트 미감지 이슈 해결 및 핸들러 리팩토링

- src/app/chat/individual/[channelRoomId]/page.tsx
- src/app/home/page.tsx
- src/components/home/ClickWebPushBanner.tsx
- src/hooks/useRegisterPushToken.ts
- src/hooks/useSocketIO.ts
- src/lib/firebase.ts
- #176
---
Firebase Messaging이 서버 사이드 렌더링(SSR) 환경에서 초기화되면서 발생하는 "This browser doesn't support the API's required to use the Firebase SDK" 에러 해결
**주요 해결 방법:**
- Firebase Messaging을 Dynamic Import로 변경하여 클라이언트 환경에서만 로드되도록 수정
- 기존 정적 import 방식에서 런타임 비동기 로딩 방식으로 전환
- 타입 안전성 개선 (any 타입 제거 및 정확한 타입 정의)
---
| 기능 유형     | 버그 수정 / 성능 개선                                  |
| 영향 범위     | Firebase 푸시 알림 관련 컴포넌트 및 훅                 |
| 관련 파일     | 있음 (firebase.ts, useRegisterPushToken.ts, ClickWebPushBanner.tsx) |
| 추가 리팩토링 | 없음 - 기존 기능 유지하면서 안정성만 개선              |
---
- [Firebase Messaging Web 가이드](https://firebase.google.com/docs/cloud-messaging/js/client)
> `Firebase Messaging` `Lazy Loading` 도입으로 SSR 호환성 개선

- package.json
- pnpm-lock.yaml
- src/app/chat/individual/[channelRoomId]/page.tsx
- src/components/layout/ClientLayoutContent.tsx
- src/contexts/SSEContext.tsx
- src/stores/modal/useChannelRoomStore.ts
- src/stores/modal/useMatchingResponseStore.ts
- src/stores/modal/useWaitingModalStore.ts
- #181
---
Zustand 스토어 사용 패턴을 개선하여 Total Blocking Time(TBT)를 감소시키고 불필요한 리렌더링을 방지했습니다.
**주요 최적화 포인트**
- React 안티패턴 제거: 컴포넌트 내 getState() 직접 호출을 selector 패턴으로 변경
- 중복 구독 최적화: useShallow를 활용한 선택적 구독으로 리렌더링 최소화
- 불변성 관리 개선: immer 미들웨어 도입으로 객체 복사 오버헤드 제거
- 메인 스레드 블로킹 해결: localStorage 비동기 처리
---
| 기능 유형     | 성능 최적화 / 리팩토링  |
| 영향 범위     | 전역 상태 관리 (Zustand 스토어), 채팅 페이지, 레이아웃 컴포넌트  |
| 관련 파일     | 있음 - 10개 Zustand 스토어, 주요 컴포넌트 4개   |
| 추가 리팩토링 | 없음 - 성능 최적화 완료 |
---
```tsx
// ❌ Before: getState() 직접 호출
useChannelRoomStore.getState().setRelationType(channelRoomId, relationType);
// ✅ After: React hook 패턴
const setRelationType = …
```
> 채팅 상세 페이지 Zustand 성능 최적화

- package.json
- pnpm-lock.yaml
- src/app/chat/individual/[channelRoomId]/page.tsx
- src/app/chat/individual/page.tsx
- src/app/providers.tsx
- #182
---
채팅 상세 페이지의 TBT(Total Blocking Time) 개선을 위한 종합적인 Tanstack Query 최적화를 진행했습니다.
1. **전역 QueryClient 설정 최적화** - 캐시 정책 및 retry 로직 개선
2. **채팅 상세 페이지 Query 최적화** - select 옵션 및 메모리 관리
3. **메시지 상태 관리 최적화** - 중복 검사 알고리즘 개선
4. **컴포넌트 메모이제이션 강화** - useMemo 및 커스텀 비교 함수
5. **Prefetching 구현** - 사용자 행동 예측 기반 데이터 사전 로드
6. **Query Invalidation 최적화** - 디바운스를 통한 중복 호출 방지
---
| 기능 유형     | 성능 최적화 / 기능 개선  |
| 영향 범위     | 전역 QueryClient, 채팅 목록 페이지, 채팅 상세 페이지   |
| 관련 파일     | 있음 (providers.tsx, 채팅 관련 페이지들)  |
| 추가 리팩토링 | 없음 (최적화 완료) |
**1. 전역 설정 최적화 (`src/app/providers.tsx`)**
```tsx
// 캐시 정책 개선
staleTime: 1000 * 60 * 5,  // 5분 캐시 유지
gcTime: 1000 * 60 * 10, …
```
> 채팅 상세 페이지 Tanstack Query 성능 최적화
