100-hours-a-week/2-hertz-fe

src/components/matching/MatchingSignalInputBox.tsx, src/components/matching/individual/KeywordTagGroup.tsx, src/components/onboarding/information/OnboardingInformationWrapper.tsx, src/components/onboarding/interests/EnumSelectGrid.tsx
- #20 
---
- 온보딩 이탈 사용자에 대한 repsonse인 `USER_INTERESTS_NOT_SELECTED` 연결 및 로직 구현
- <input>에서 Enter 키를 누르면 button 클릭 이벤트까지 중복 호출하는 문제 수정
- 온보딩 중 10개 이상 클릭 시 뜨는 토스트 메세지 다중 호출 방지를 위한 id 부여
- 튜닝 페이지 공통 관심사 존재하지 않을 때 안내 문구 구현
- 시그널 보내는 도중 채팅방 생성 시 알림 처리
---
| 기능 유형     | 신규 기능 / 기능 개선 / 버그 수정 / UI 변경 등         |
=> 온보딩 도중 이탈한 사용자 예외처리 및 기타 UX 에러 수정

.github/workflows/cicd-frontend.yml
- x
---
- cd 실패 exit 1로 종료되는 트리거를 rollback job에서 인식하지 못해 문제가 생김
- rollback job의 트리거에 `if: always() && needs.frontend-cd.result != 'success'`를 설정
- cd job에서 exit 1을 뱉고 끝내더라도, rollback job에 `always()`를 넣어 해당 job을 인식하게 설정하고, `&& needs.frontend-cd.result != 'success'` 조건을 추가로 걸어 cd job이 실패했을 때만 수행됨
---
- x
---
- x
---
- x
=> fix: cd 실패 시 rollback으로 넘어가지 않는 오류 수정

.github/workflows/cicd-frontend.yml
- x
---
- cd 실패 exit 1로 종료되는 트리거를 rollback job에서 인식하지 못해 문제가 생김
- rollback job의 트리거에 `if: always() && needs.frontend-cd.result != 'success'`를 설정
- cd job에서 exit 1을 뱉고 끝내더라도, rollback job에 `always()`를 넣어 해당 job을 인식하게 설정하고, `&& needs.frontend-cd.result != 'success'` 조건을 추가로 걸어 cd job이 실패했을 때만 수행됨
---
- x
---
- x
---
- x
=> CICI에서 CD 실패 시 rollback으로 넘어가지 않는 오류 수정 (#55)

src/components/layout/BottomNavigationBar.tsx, src/components/layout/ChatHeader.tsx, src/components/layout/ClientLayoutContent.tsx, src/components/layout/Header.tsx
- #57 
---
- 헤더 아이콘 크기 조정
- 모바일 콘텐츠 영역에 그림자 효과 추가
- 하단 네비게이션 버튼 map 기반 리팩토링 및 UI 개선 (그림자 효과 추가, 항목 클릭 시 UI 변경)
---
| 기능 유형     |  UI 변경        |
=> 하단 네비게이션 리팩토링 및 배경 그림자 추가로 UI 개선

src/app/chat/individual/[channelRoomId]/page.tsx, src/app/chat/individual/page.tsx, src/app/profile/[partnerId]/page.tsx, src/components/chat/common/ReceiverMessage.tsx, src/components/chat/common/SenderMessage.tsx, src/components/layout/ChatHeader.tsx, src/components/layout/ClientLayoutContent.tsx, src/lib/api/matching.ts
- #79
---
- 매칭 SSE 모달 - 수락 / 거절 api 연결
- `useParams` 사용으로 상대방 프로필 상세페이지 정상 표시되도록 수정
- 매칭 시 채팅방 내부 컴포넌트 색상 변경
- 채팅방 헤더 아이콘 삭제
---
| 기능 유형     | 신규 기능 / 기능 개선 / UI 변경 등         |
---
---
매칭 모달 안 닫히는 문제 트러블슈팅
일반관심사 / 공통관심사 분리 트러블슈팅 진행 예정
=> 매칭 SSE 수락/거절 API 연동 및 채팅방 UI 동적 반영

src/app/mypage/page.tsx, src/app/profile/[partnerId]/page.tsx, src/app/report/page.tsx, src/components/common/KeywordTag.tsx, src/components/matching/individual/KeywordTagGroup.tsx, src/lib/api/matching.ts, src/lib/api/user.ts
- #87
---
- 마이페이지 및 프로필 상세보기에서 공통 관심사와 일반 관심사가 분리되지 않는 문제 해결
- 매칭되지 않은 사용자의 일반 관심사 키워드 블러 처리 로직 추가
---
| 기능 유형     | 버그 수정 / UI 변경   |
=> 공통 / 일반 관심사 분리 및 매칭되지 않은 사용자 키워드 블러 처리

src/app/alarm/page.tsx, src/app/chat/individual/[channelRoomId]/page.tsx, src/app/globals.css, src/app/profile/[partnerId]/page.tsx, src/app/report/page.tsx, src/components/chat/UnavailableChannelBanner.tsx, src/components/common/ConfirmModal.tsx, src/components/common/LoadingSpinner.tsx, src/components/common/WaitingModal.tsx, src/components/layout/ChatHeader.tsx, src/components/layout/ClientLayoutContent.tsx, src/components/matching/individual/KeywordTagGroup.tsx, src/stores/modal/useWaitingModalStore.ts
- #91
---
- 채팅방 헤더 닉네임 클릭 시 상세정보 페이지로 이동
- 프로필 상세보기 뒤로가기 버튼 추가
- 공통 로딩 컴포넌트로 사용하기 위한 범용적 문구 수정
- 튜닝 페이지에서 일반 관심사 관련 문구 숨김 처리
- 튜닝 리포트마다 각각 날짜가 뜨지 않는 문제 수정
- `ConfirmModal` 닫기 버튼 제거
- 채팅방 헤더 화살표 클릭 시 상세페이지 이동 기능 활성화
- 매칭 토스트 메시지 노출 시간 1000ms → 4000ms로 수정
- 매칭 응답 대기 중 모달이 떠 있는 상태에서도 채팅방에서 정상적으로 나갈 수 있도록 로직 수정
- 매칭 실패 시 안내 문구를 중립적인 표현으로 수정
- 알림 단어 단위 줄바꿈을 위한 `text-wrap-keep` 유틸 클래스 추가
- 매칭 결정 알림 SSE 연결
---
| 기능 유형     | 신규 기능 / 기능 개선 / 버그 수정 / UI 변경   |
=> v1 QA 기반 수정사항 반영 및 매칭/채팅/알림 개선

src/app/chat/individual/[channelRoomId]/page.tsx, src/components/common/ConfirmModal.tsx, src/components/layout/BottomNavigationBar.tsx, src/lib/api/chat.ts
- #94
---
- 채팅방 나가기 API 연결 및 모달 로직 연결
- 채팅방 외 다른 페이지 클릭 시 `WaitingModal`이 닫히도록 수정
---
| 기능 유형     | 신규 기능 / 버그 수정     |
=> 채팅방 나가기 API 연결

src/components/common/NewMessageToast.tsx, src/components/layout/ClientLayoutContent.tsx, src/components/matching/individual/KeywordTagGroup.tsx, src/hooks/useSSE.ts, src/stores/modal/useNewMessageStore.ts
- #98
---
- 메세지 수신 SSE `new-message-reception` 이벤트 로직 구현
- 메시지 수신 시 팝업 알림(`NewMessageToast`) UI 퍼블리싱
- 상태 관리를 위한 `useNewMessageStore` 상태 훅 적용
- 디버깅용 `console.log` 제거
https://github.com/user-attachments/assets/709aa3bb-7826-48cf-9393-9e9ee9d55c3d
---
| 기능 유형     | 신규 기능 / 기능 개선 / 버그 수정 / UI 변경 등         |
=> 새 메세지 수신 SSE 연결 및 팝업 알림 UI 구현

src/app/chat/individual/[channelRoomId]/page.tsx, src/components/common/NewMessageToast.tsx, src/components/layout/ClientLayoutContent.tsx, src/components/onboarding/information/UserInformationForm.tsx, src/hooks/useSSE.ts, src/lib/schema/onboardingValidation.ts, src/stores/modal/useMatchingResponseStore.ts
- #103
---
**버그 수정**
- 새 메세지 수신 팝업이 표시되지 않던 문제 해결
- `ConfirmModal` 응답 이전에는 `UnavailableChannelBanner`가 표시되지 않도록 수정
- 매칭 거절 시 SSE 모달과 거절 배너가 동시에 노출되는 문제 수정
- `useMemo` 제거로 `eventSource` 연결 안 되는 이슈 해결
**기능 개선**
- 채팅방 나가기 모달 문구 수정
**예외 처리**
- 로그인 / 온보딩 페이지에서 SSE 호출 방지
- 온보딩 한줄소개 zod 스키마 최소 10자 검증 시 공백 제외하도록 수정
- 현재 접속 중인 채팅방에서는 새 메세지 토스트가 표시되지 않도록 예외 처리 로직 추가
- 온보딩 중 등록된 사용자일 때 409 상태 코드 감지하는 로직 추가
- SSE 연결 중 `heartbeat` 상태 감지 로직 추가
---
| 기능 유형     | 기능 개선 / 버그 수정 / UI 변경     |
=> SSE 버그 수정 및 QA 피드백 기반 예외 처리 개선

src/app/alarm/page.tsx, src/app/chat/individual/[channelRoomId]/page.tsx, src/app/layout.tsx, src/components/layout/AuthGuard.tsx, src/lib/api/chat.ts
- #103
---
- 이미 나간 채팅방을 알림 페이지에서 접속했을 때 예외 처리
- 브라우저 뒤로가기로 나간 채팅방에 접근했을 때 예외 처리 추가
- AuthGuard 추가 및 로그인 상태 유지 기능 구현
---
- 로그인하지 않은 유저가 브라우저 url로 다른 페이지에 접근할 수 없게 예외처리
https://github.com/user-attachments/assets/b0727b4b-3851-44d2-8e83-b719d2c474b4
---
| 기능 유형     | 기능 개선 / 버그 수정 |
=> 나간 채팅방 및 비로그인 유저 접근 예외 처리 및 `AuthGuard` 적용

src/lib/api/auth.ts
- #113
---
- Access Token 재발급 API인 `/api/v1/auth/token`에서 넘겨주는 400 에러에 대한 예외 처리 진행
---
| 기능 유형     | 기능 개선  |
=> Refresh Token 만료 시 무한 요청 방지를 위한 예외 처리 추가

src/lib/api/auth.ts
- #113
---
- Access Token 재발급 API(`/api/v1/auth/token`)에서 발생하는 400 `REFRESH_TOKEN_INVALID` 에러에 대한 예외 처리 로직 추가
- 해당 에러 발생 시 `hasLoggedIn` 값을 false로 설정하여 자동 로그인 조건을 해제
- 로그인 페이지 진입 시 불필요한 자동 로그인 시도를 차단하여 무한 리다이렉트 루프 방지
---
| 기능 유형     | 버그 수정  |
| 문제 원인   | 만료된 Refresh Token으로 인한 재발급 실패 후, 자동 로그인 로직이 반복 실행됨  |
| 해결 방법     | `REFRESH_TOKEN_INVALID` 수신 시 `localStorage`에서 `hasLoggedIn`을 false로 설정하여 자동 로그인 비활성화  |
---
- https://github.com/100-hours-a-week/2-hertz-wiki/issues/390#issue-3175534340
- 모바일과 PC에서 동시 로그인 시, Redis에 저장된 RT가 최신 로그인 디바이스 기준으로 덮어씌워짐
- 기존 디바이스에서는 만료된 RT로 AT 재발급을 시도하게 되어 400 `REFRESH_TOKEN_INVALID` 응답 발생
- 프론트는 해당 에러 발생 시 로그인 페이지로 …
=> `REFRESH_TOKEN_INVALID` 응답 시 무한 리다이렉트 이슈 해결 - 만료된 RT로 인한 자동 로그인 루프 방지

src/app/mypage/page.tsx
- #131
---
- 마이페이지에서 한 줄 소개 저장 후 GET `/api/v2/users/{userId}`가 무한 호출되는 문제 수정
- 문제의 원인은 useEffect의 의존성 배열에 userInfo가 포함되어 있어, 상태 변경 → 다시 fetch → 다시 상태 변경의 무한 루프가 발생함
- 의존성 배열을 userId로 수정하여 API가 단 1회만 호출되도록 개선
---
```ts
useEffect(() => {
const fetchUserInfo = async () => {
if (!userId) {
console.error('userId가 없습니다.');
return;
}
try {
const response = await getUserInfo(userId);
setUserInfo(response.data);
} catch (error) {
console.error('유저 정보 불러오기 실패: ', error);
}
};
fetchUserInfo();
}, [userInfo]); ⬅️ 
```
---
1. `userInfo`가 null이기 때문에 처음에 `fetchUserInfo()` 실행됨
2. `setUserInfo(response.data)`가 실행되며 `userInfo`가 변경됨
3. `userInfo`가 변경되면 `useEffect(..., [userInfo])`가 다시 실행됨 → 또 `fetchUserInfo()` 호출
4. 다시 `setUserInfo()` → 다시 `userInfo` 변경 → 무한 반복
---
```ts
useEffect(() => {
const …
```
=> 마이페이지에서 `userInfo` 의존성으로 인한 사용자 정보 API 무한 호출 문제 해결

src/app/chat/individual/[channelRoomId]/page.tsx, src/components/common/ConfirmModal.tsx, src/constants/sseHandlers.tsx, src/stores/modal/useMatchingResponseStore.ts
- #155
---
- **응답중 모달이 떴을 때 채팅 입력창 비활성화**
- 채팅방 진입 후 상대방이 매칭 응답 중일 때 띄워지는 `WaitingModal`이 열려 있을 경우, 사용자가 메시지를 입력하지 못하도록 채팅 입력창을 비활성화함
-` useWaitingModalStore().shouldShowModal` 값을 감지하여 조건 제어
- **매칭 모달이 채팅 목록에서 뜨지 않도록 예외 처리 추가**
- 채팅 목록(`/chat`) 페이지에서도 `WaitingModal` 또는 `ConfirmModal`이 뜨는 현상 방지
- pathname 조건(`/chat/individual`)으로 제한하여 목록 페이지에서는 매칭 응답 모달이 뜨지 않도록 처리
- **매칭 확인 모달이 채팅 상세 페이지에서만 뜨도록 경로 제한**
- 매칭 수락/거절 확인을 위한 `ConfirmModal`이 오직 채팅 상세 페이지에서만 노출되도록 경로 기반 조건 추가
- 잘못된 위치에서 매칭 응답 모달이 떠서 혼란을 주던 문제 해결
- **매칭 거절 시 제한 배너가 바로 뜨지 않는 문제 해결**
- 사용자가 매칭을 거절한 직후 `relationType: UNMATCHED` 상태가 반영되었음에도,
채팅 입력창 위 제한 배너(`UnavailableChannelBanner`)가 바로 렌더링되지 않던 문제를 수정
- 상태 변경 후 강제로 상태를 업데이트해 바로 UI가 반영되도록 개선
https://github.com/user-attachments/assets/a9195beb-5bc7-4c4a-8f59-cd440e8a4b9f
---
| 항목 …
=> 응답 중 입력창 비활성화 및 매칭 거절 시 제한 배너 표시 로직 개선

src/components/common/ConfirmModal.tsx
- #158
---
- `ConfirmModal`이 마이페이지에서 로그아웃 모달까지 차단하던 문제 해결
- `ConfirmModal`이 채팅 상세 경로(`/chat/individual/:id`)에서만 뜨도록 제한되어 있어, 마이페이지에서 로그아웃 모달이 렌더링되지 않던 이슈 해결
- 마이페이지에서는 로그아웃 `ConfirmModal`이 정상적으로 뜨도록 예외 조건 분기 처리
---
| 기능 유형     | 버그 수정  |
=> 마이페이지에서 ConfirmModal이 렌더링되지 않던 문제 수정

public/firebase-messaging-sw.js, public/service-worker.js
- #151 
---
- FCM 푸시 알림 클릭 시 사용자가 홈(/) 페이지로 이동하도록 처리
- 푸시 알림에 title, content가 없는 경우, 예외 상황에도 사용자에게 자연스러운 메시지가 노출되도록 fallback 처리
---
| 기능 유형     | 기능 개선   |
---
- 현재는 홈 페이지로만 이동하도록 처리했으며, 추후 알림 유형에 따라 라우팅 분기 처리 예정입니다.
- 푸시 알림 기본 문구는 서버 응답 형식이 변경되면 별도로 핸들링을 위한 수정이 필요할 수 있습니다.
=> FCM 푸시 알림 클릭 시 홈으로 이동 처리 및 기본 문구 적용

public/firebase-messaging-sw.js, public/service-worker.js
- #151 
---
- FCM 푸시 알림 클릭 시 사용자가 홈(/) 페이지로 이동하도록 처리
- 푸시 알림에 title, content가 없는 경우, 예외 상황에도 사용자에게 자연스러운 메시지가 노출되도록 fallback 처리
- 모든 알림을 개별적으로 표시하기 위해 tag 제거
---
| 기능 유형     | 기능 개선 / 버그 수정   |
---
- 현재는 홈 페이지로만 이동하도록 처리했으며, 추후 알림 유형에 따라 라우팅 분기 처리 예정입니다.
- 푸시 알림 기본 문구는 서버 응답 형식이 변경되면 별도로 핸들링을 위한 수정이 필요할 수 있습니다.
=> FCM 알림 tag 설정으로 인한 중복 알림 미표시 문제 해결

src/app/chat/individual/[channelRoomId]/page.tsx, src/components/common/ConfirmModal.tsx, src/components/layout/ChatHeader.tsx, src/components/layout/ClientLayoutContent.tsx, src/constants/sseHandlers.tsx, src/stores/modal/useConfirmModalStore.ts, src/stores/modal/useMatchingResponseStore.ts, src/stores/modal/useNewMessageStore.ts, src/stores/modal/useWaitingModalStore.ts, src/types/chat.ts
- #170
---
1. **UNMATCHED 상태 채팅 제한 버그 수정**
- `relationType='UNMATCHED'`일 때 `hasResponded` 조건과 관계없이 무조건 채팅 제한 적용
- SSE 연결 안정성 개선 (불필요한 재연결 로직 제거)
2. **모달 임시 숨김/복원 시스템 구현**
- 브라우저 뒤로가기 시 매칭 모달, 응답중 모달을 임시로 숨기고 다시 채팅방에 돌아왔을 때 복원하는 기능
- `ConfirmModal`, `WaitingModal`, `MatchingResponseModal` 모두 적용
3. **전역 모달 관리 시스템 적용**
- 모바일 스와이프, 마우스 뒤로가기 버튼, 헤더 버튼 등 모든 네비게이션 방식 지원
- `ClientLayoutContent`에서 전역적으로 모달 상태 관리
4. **SSE 메시지 알림 개선**
- `lastPageNumber` 필드 추가로 정확한 페이지네이션 지원
- 첫 시그널과 일반 메시지 모두 통일된 토스트 UI로 표시
---
| 기능 유형     | 버그 수정 / 기능 개선 / 신규 기능                      |
| 영향 범위     | 채팅방 페이지, 모달 컴포넌트, SSE 핸들러, 토스트 알림  |
| 추가 리팩토링 | 없음 …
=> 채팅방 `UNMATCHED` 상태 채팅 제한 및 전역 모달 상태 관리 개선

src/app/chat/individual/[channelRoomId]/page.tsx, src/hooks/useSocketIO.ts
- #174
---
- 채팅방 WebSocket 연결 안정성 및 자동 재연결 기능 구현
- 채팅방 최초 진입 시 WebSocket 연결 실패 → 새로고침 전까지 소켓 연결이 이루어지지 않음
- 네트워크 불안정 시 수동 복구 필요 → 연결 끊김 시 사용자가 직접 새로고침해야 함
- 연결 확인 없이 메시지 전송을 시도해 전송 실패 가능성이 있음
**1. WebSocket 연결 안정성 강화**
- 자동 재연결 메커니즘 구현 (최대 5회, 점진적 지연 구현 `2초 → 4초 → 6초`)
- 10초 타임아웃 설정으로 빠른 실패 감지
- 중복 연결 시도 방지 및 리소스 정리 최적화
- `forceNew` 옵션 제거로 불필요한 새 연결 생성 방지
**2. 실시간 연결 상태 추적**
- `isConnected` 상태로 연결 여부 실시간 모니터링
- `reconnect()` 함수로 수동 재연결 기능 제공
- 연결 상태 변화에 따른 UI 즉시 반영
**3. 사용자 경험 개선**
- 연결 상태별 입력창 비활성화 및 안내 메시지
- 연결 끊김 시 토스트 알림 및 3초 후 자동 재연결
- 메시지 전송/읽음 처리 전 연결 상태 선행 체크
- 연결 실패 시 명확한 오류 메시지 및 자동 복구 시도
---
| 기능 유형     | **버그 수정** + **기능 개선** …
=> 채팅방 최초 진입 시 WebSocket 연결 실패 및 안정성 문제 해결
